# Setup
title:        NH Studio Official Website
tagline:      Trang web chính thức của NH Studio
baseurl:      ""
paginate:     1
locale:       "vi"

# About/contact
author:
  name:       NH Studio
  url:        https://nhstudiovn.xyz

# Gems
gems:
  - jekyll-paginate
  - jekyll-seo-tag

#Others
markdown: kramdown
